version: "3"
services:
  backend:
    image: ${DOCKER_USERNAME}/dong-gle-backend-load-test:latest
    expose:
      - 8080
    volumes:
      - /home/ubuntu/logs/:/logs/
    environment:
      - SPRING_PROFILES_ACTIVE
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 1.5g

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - /home/ubuntu/certs/:/etc/nginx/certs/
      - ./conf-${INFRA_PROFILE}/:/etc/nginx/conf.d/
      - /home/ubuntu/nginx-logs/:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
